---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: demo
    networking.gke.io/v1beta1.FrontendConfig: demo
    networking.gke.io/managed-certificates: demo
spec:
  defaultBackend:
    service:
      name: demo
      port:
        number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: demo
spec:
  type: NodePort
  selector:
    app: demo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 7001
  type: LoadBalancer  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  labels:
    app: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: europe-central2-docker.pkg.dev/GOOGLE_PROJECT/docker-images/tma-back-image:IMAGE_TAG
        ports:
        - containerPort: 7001