---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: back-demo
spec:
  redirectToHttps:
    enabled: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: back-demo
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: back-demo
    networking.gke.io/v1beta1.FrontendConfig: back-demo
    networking.gke.io/managed-certificates: back-demo
spec:
  defaultBackend:
    service:
      name: back-demo
      port:
        number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: back-demo
spec:
  type: NodePort
  selector:
    app: demo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 7001
  type: LoadBalancer  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-demo
  labels:
    app: back-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: back-demo
  template:
    metadata:
      labels:
        app: back-demo
    spec:
      containers:
      - name: back-demo
        image: europe-central2-docker.pkg.dev/GOOGLE_PROJECT/docker-images/tma-back-image:IMAGE_TAG
        ports:
        - containerPort: 7001